---
title: "Predictor Exploration"
author: "Connor French"
date: "10/29/2020"
output: html_document
---

```{r}
library(raster)
library(tidyverse)
library(sf)
library(here)
library(tmap)
```


Read in data sets
```{r}
med_100 <- read_sf(here("output", "spreadsheets", "medium_100.geojson"),
                   crs = "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs") %>% 
  select(-contains("terrain"), -contains("land_cover")) %>% 
  mutate(otu_min = factor(100))
med_150 <- read_sf(here("output", "spreadsheets", "medium_150.geojson"),
                   crs = "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs") %>% 
  select(-contains("terrain"), -contains("land_cover")) %>% 
  mutate(otu_min = factor(150))
med_200 <- read_sf(here("output", "spreadsheets", "medium_200.geojson"),
                   crs = "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs") %>% 
  select(-contains("terrain"), -contains("land_cover")) %>% 
  mutate(otu_min = factor(200))
```


```{r}
template_medium_rast <- raster(here("data", "templates", "template_medium.tif"))

new_stab_files <- list.files("~/Downloads/data/past_climate", full.names = TRUE)

new_stab_rasters <- stack(new_stab_files)

new_stab_sf <- new_stab_rasters %>%  
  projectRaster(template_medium_rast) %>% 
  rasterToPolygons() %>% 
  st_as_sf()

# take the median of all overlapping cells with each of the medium resolution cells
med_100_sf <- st_join(med_100, 
                         new_stab_sf,
                         largest = TRUE)
med_100_df <- med_100_sf %>% 
  mutate(temp_trend = GlobalExtreme_tsTrendExt,
         temp_var = GlobalExtreme_tsVarExt,
         precip_trend = GlobalExtreme_prTrendExt,
         precip_var = GlobalExtreme_prVarExt)

med_150_sf <- st_join(med_150, 
                         new_stab_sf,
                         largest = TRUE)
med_150_df <- med_150_sf %>% 
  mutate(temp_trend = GlobalExtreme_tsTrendExt,
         temp_var = GlobalExtreme_tsVarExt,
         precip_trend = GlobalExtreme_prTrendExt,
         precip_var = GlobalExtreme_prVarExt)

med_200_sf <- st_join(med_200, 
                         new_stab_sf,
                         largest = TRUE)
med_200_df <- med_200_sf %>% 
  mutate(temp_trend = GlobalExtreme_tsTrendExt,
         temp_var = GlobalExtreme_tsVarExt,
         precip_trend = GlobalExtreme_prTrendExt,
         precip_var = GlobalExtreme_prVarExt)
  
```




Base map
```{r}
base_map <- rnaturalearth::ne_countries(returnclass = "sf")
```

Map global temperature trend
```{r}
ggplot() +
  geom_sf(data = new_stab_sf, aes(fill = GlobalExtreme_tsTrendExt, color = GlobalExtreme_tsVarExt)) +
  scale_fill_viridis_c() +
  scale_color_viridis_c()
```




Map hill 1 in all three data sets
```{r}
tmap_mode("view")
tm_shape(base_map) +
  tm_borders() + 
  tm_shape(med_100_df) +
  tm_polygons(col = "stability_temp_medium", palette = "viridis") +
  tm_shape(med_150_df) +
  tm_polygons(col = "stability_temp_medium", palette = "viridis") +
  tm_shape(med_200_df) +
  tm_polygons(col = "stability_temp_medium", palette = "viridis")
```


Combine dfs
```{r}
med_all <- bind_rows(med_100_df, med_150_df, med_200_df)
```

```{r}
ggplot(data = med_all, aes(x = temp_trend, y = hill_1, color = min_temp)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~otu_min)
```



```{r}
ggplot(data = med_150_df %>% filter(hill_1 > 0.34), aes(x = temp_trend, y = current_medium_bio_5)) +
  geom_point() +
  geom_smooth(method = "lm") +
  NULL
```


