---
title: "R Notebook"
output: html_notebook
---

```{r}
library(vegan)
library(tidyverse)
library(sf)
```

Read in final data set and raw pi data set
```{r}
df_150 <- st_read("/Users/connorfrench/Dropbox/Old_Mac/School_Stuff/CUNY/BigAss-bird-phylogeography/BigAss-phylogeography/output/spreadsheets/medium_150.geojson") %>% 
  filter(hill_1 > 0.35)

st_crs(df_150) <- "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs"

df_pi <- read_csv("/Users/connorfrench/Dropbox/Old_Mac/School_Stuff/CUNY/BigAss-bird-phylogeography/BigAss-phylogeography/output/spreadsheets/cell_medium_3_20_pi.csv")
```

Filter pi df for cells that are within the final data frame
```{r}
df_pi_filt <- df_pi %>% 
  filter(cell %in% df_150$cell)
```

Top 5 orders
```{r}
df_pi_filt %>% 
  count(order) %>% 
  arrange(desc(n)) %>% 
  slice(1:5) %>% 
  mutate(order = fct_reorder(order, n)) %>% 
  ggplot() +
  geom_col(aes(x = order, y = n)) +
  coord_flip()
```

Histograms of low, medium, and high Hill number cells
```{r}
df_pi_filt %>% 
  filter(cell %in% c(825, 5448, 3093)) %>% 
  mutate(cell = factor(cell),
         hill_rank = case_when(
           cell == 825 ~ "Low",
           cell == 3093 ~ "High",
           TRUE ~ "Medium"
         ),
         hill_rank = fct_relevel(hill_rank, c("High", "Medium", "Low"))) %>% 
  ggplot() +
  geom_density(aes(x = pi, color = hill_rank), adjust = 3) +
  scale_color_viridis_d() +
  labs(x = "Average number pf pairwise nucleotide differences",
       y = "Frequency",
       color = "GE rank") +
  theme_minimal()

```

NEED TO GO BACK AND MAKE SURE OTHER HILL NUMBERS ARE NOT NORMALIZED
```{r}
df_150 %>% 
  filter(min_temp == "temperate") %>% 
  pivot_longer(cols = contains("hill_"), 
               names_to = "hill_q",
               values_to = "hill_number") %>% 
  ggplot() +
  geom_density(aes(x = hill_number, color = hill_q))
```


## Beta diversity

Create a presence-absence matrix of each cell
```{r}
# filter localities for unique OTUs. There are 
df_unique <- df_pi_filt %>% 
  group_by(cell) %>% 
  filter(!duplicated(bin_uri)) %>% 
  ungroup() %>% 
  select(cell, bin_uri)

presabs_mat <- table(df_unique)
```


```{r}
jaccard_beta <- vegdist(presabs_mat, 
                        method = "jaccard", 
                        binary=TRUE,
                        upper = TRUE) %>% 
  as.matrix()
```

```{r}
heatmap(jaccard_beta)
```



```{r}
jaccard_xy <- t(combn(colnames(jaccard_beta), 2))

jaccard_df <- tibble(cell_1 = jaccard_xy[,1], 
                     cell_2 = jaccard_xy[,2],
                     dist = jaccard_beta[jaccard_xy])
```

Average beta diversity
```{r}
jaccard_avg <- jaccard_df %>% 
  group_by(cell_1) %>% 
  summarize(avg_beta = mean(dist)) %>% 
  rename(cell = cell_1) %>% 
  mutate(cell = as.double(cell))
```

Combine with original data frame
```{r}
df_beta <- left_join(df_150, jaccard_avg, by = "cell") 
  
```


```{r}
df_beta %>% 
  mutate(log_beta = log(avg_beta)) %>% 
  ggplot() +
  geom_sf(aes(fill = avg_beta, color = avg_beta)) +
  scale_fill_viridis_c() +
  scale_color_viridis_c()
```

```{r}
df_beta %>% 
  mutate(log_beta = log(avg_beta)) %>% 
  ggplot(aes(x = avg_beta, y = hill_1)) +
  geom_point() +
  geom_smooth()
```


```{r}
df_beta %>% 
  mutate(log_beta = log(avg_beta)) %>% 
  ggplot(aes(x = min_temp, y = avg_beta)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.7, width = 0.2)
```


```{r}
biome_shp <- st_read("/Users/connorfrench/Dropbox/Old_Mac/School_Stuff/CUNY/BigAss-bird-phylogeography/BigAss-phylogeography/data/climate_poly/Ecoregions2017/Ecoregions2017.shp")

```

```{r}
biomes <- biome_shp %>% 
  select(BIOME_NAME, BIOME_NUM) %>% 
  st_transform(crs = "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs")



df_biomes <- st_join(x = df_150 %>% , y = biomes, largest = TRUE)


```


